"""add nts columns

Revision ID: 36377f572972
Revises: 98d45eecb661
Create Date: 2026-05-07 14:44:41.642320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36377f572972'
down_revision = '98d45eecb661'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    existing = {col['name'] for col in sa.inspect(bind).get_columns('appliance')}

    with op.batch_alter_table('appliance', schema=None) as batch_op:
        if 'new_to_service' not in existing:
            batch_op.add_column(sa.Column('new_to_service', sa.Boolean(), nullable=True))
        if 'entry_to_service_date' not in existing:
            batch_op.add_column(sa.Column('entry_to_service_date', sa.Date(), nullable=True))
        if 'default_retest_interval_days' not in existing:
            batch_op.add_column(sa.Column('default_retest_interval_days', sa.Integer(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appliance', schema=None) as batch_op:
        batch_op.drop_column('default_retest_interval_days')
        batch_op.drop_column('entry_to_service_date')
        batch_op.drop_column('new_to_service')

    # ### end Alembic commands ###
