"""initial schema

Revision ID: 98d45eecb661
Revises: 
Create Date: 2026-04-29 05:37:26.504123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d45eecb661'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appliance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_number', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('make_model', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('class_type', sa.String(length=50), nullable=True),
    sa.Column('supply_type', sa.String(length=50), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('receipt_filepath', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('disposed', sa.Boolean(), nullable=True),
    sa.Column('disposal_date', sa.Date(), nullable=True),
    sa.Column('disposal_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('disposal_comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_number')
    )
    op.create_table('retest_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_type', sa.String(length=50), nullable=True),
    sa.Column('supply_type', sa.String(length=50), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('certificate_number', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repair_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appliance_id', sa.Integer(), nullable=False),
    sa.Column('repair_date', sa.Date(), nullable=False),
    sa.Column('repaired_by', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('locked_by_test_date', sa.Date(), nullable=True),
    sa.Column('disposed', sa.Boolean(), nullable=True),
    sa.Column('parts_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('labour_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appliance_id'], ['appliance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appliance_id', sa.Integer(), nullable=False),
    sa.Column('tester_id', sa.Integer(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('test_type', sa.String(length=255), nullable=False),
    sa.Column('test_standard', sa.String(length=50), nullable=False),
    sa.Column('tag_number', sa.String(length=255), nullable=False),
    sa.Column('next_test_due', sa.Date(), nullable=True),
    sa.Column('overall_result', sa.String(length=10), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('disposed', sa.Boolean(), nullable=True),
    sa.Column('vi_plug', sa.Boolean(), nullable=True),
    sa.Column('vi_cord', sa.Boolean(), nullable=True),
    sa.Column('vi_overheat', sa.Boolean(), nullable=True),
    sa.Column('vi_exposed', sa.Boolean(), nullable=True),
    sa.Column('vi_casing', sa.String(length=50), nullable=True),
    sa.Column('vi_label', sa.String(length=50), nullable=True),
    sa.Column('vi_repairs', sa.String(length=10), nullable=True),
    sa.Column('vi_strain', sa.String(length=10), nullable=True),
    sa.Column('vi_guards', sa.String(length=10), nullable=True),
    sa.Column('earth_continuity_ohms', sa.String(length=50), nullable=True),
    sa.Column('insulation_mohms', sa.String(length=50), nullable=True),
    sa.Column('leakage_mA', sa.String(length=50), nullable=True),
    sa.Column('polarity_pass', sa.String(length=50), nullable=True),
    sa.Column('condition_assessment', sa.String(length=255), nullable=True),
    sa.Column('functional_check', sa.String(length=255), nullable=True),
    sa.Column('accessories', sa.String(length=255), nullable=True),
    sa.Column('safe_for_resale', sa.String(length=255), nullable=True),
    sa.Column('repair_description', sa.Text(), nullable=True),
    sa.Column('repaired_by', sa.String(length=255), nullable=True),
    sa.Column('parts_replaced', sa.Text(), nullable=True),
    sa.Column('post_repair_test', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['appliance_id'], ['appliance.id'], ),
    sa.ForeignKeyConstraint(['tester_id'], ['tester.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repair_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repair_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['repair_id'], ['repair_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['test_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_photo')
    op.drop_table('repair_photo')
    op.drop_table('test_record')
    op.drop_table('repair_record')
    op.drop_table('tester')
    op.drop_table('retest_rule')
    op.drop_table('appliance')
    # ### end Alembic commands ###
